### ISSUE TITLE
Error el.exe is not path

### ISSUE THREAD

**Issue by vanloc0301** [elixir-cn/elixir-china#68]
I have error when compile with command `mix ecto.create Repo`

`
'cl.exe' is not recognized as an internal or external command,
operable program or batch file.
ERROR: compile failed while processing c:/Users/opami/Desktop/elixir-china/deps/bcrypt: rebar_abort
==> elixir_china
** (Mix) Could not compile dependency :bcrypt, "escript.exe "c:/Users/opami/.mix/rebar"" command failed. You can recompile this dependency with "mix deps.compile bcrypt", update it with "mix deps.update bcrypt" or clean it with "mix deps.clean bcrypt"
`
How to resolve this error? Thanks

**Comment by tony612** [comment]
Did you try `mix deps.clean bcrypt`?

**Comment by vanloc0301** [comment]
I was clean bcrypt and recompile but error also like this. I wasn't install `Escript.exe`

**Comment by tony612** [comment]
I think it's because of your Elixir environment on Windows. What's strange is `cl.exe` seems not related to Elixir.
