### ISSUE TITLE
"mix ecto.create Repo"遇错，如何解决？

### ISSUE THREAD

**Issue by luckypoem** [elixir-cn/elixir-china#75]
hi.

root@hb:~/elixir-china# mix ecto.create Repo
warning: variable "deps" does not exist and is being expanded to "deps()", please use parentheses to remove the ambiguity or change the variable name
  mix.exs:12

warning: variable "description" does not exist and is being expanded to "description()", please use parentheses to remove the ambiguity or change the variable name
  /root/elixir-china/deps/uuid/mix.exs:8

warning: variable "package" does not exist and is being expanded to "package()", please use parentheses to remove the ambiguity or change the variable name
  /root/elixir-china/deps/uuid/mix.exs:9

warning: variable "deps" does not exist and is being expanded to "deps()", please use parentheses to remove the ambiguity or change the variable name
  /root/elixir-china/deps/uuid/mix.exs:10

===> Compiling bcrypt
make: Entering directory '/root/elixir-china/deps/bcrypt/c_src'
cc    bcrypt_port.c bcrypt.o blowfish.o   -lpthread -o ../priv/bcrypt
cc: error: bcrypt.o: No such file or directory
cc: error: blowfish.o: No such file or directory
Makefile:4: recipe for target '../priv/bcrypt' failed
make: **\* [../priv/bcrypt] Error 1
make: Leaving directory '/root/elixir-china/deps/bcrypt/c_src'
===> Hook for compile failed!

*\* (Mix) Could not compile dependency :bcrypt, "/root/.mix/rebar3 bare compile --paths "/root/elixir-china/_build/dev/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile bcrypt", update it with "mix deps.update bcrypt" or clean it with "mix deps.clean bcrypt"
root@hb:~/elixir-china#
root@hb:~/elixir-china# mix deps.compile bcrypt
warning: variable "deps" does not exist and is being expanded to "deps()", please use parentheses to remove the ambiguity or change the variable name
  mix.exs:12

warning: variable "description" does not exist and is being expanded to "description()", please use parentheses to remove the ambiguity or change the variable name
  /root/elixir-china/deps/uuid/mix.exs:8

warning: variable "package" does not exist and is being expanded to "package()", please use parentheses to remove the ambiguity or change the variable name
  /root/elixir-china/deps/uuid/mix.exs:9

warning: variable "deps" does not exist and is being expanded to "deps()", please use parentheses to remove the ambiguity or change the variable name
  /root/elixir-china/deps/uuid/mix.exs:10

===> Compiling bcrypt
make: Entering directory '/root/elixir-china/deps/bcrypt/c_src'
cc    bcrypt_port.c bcrypt.o blowfish.o   -lpthread -o ../priv/bcrypt
cc: error: bcrypt.o: No such file or directory
cc: error: blowfish.o: No such file or directory
Makefile:4: recipe for target '../priv/bcrypt' failed
make: **\* [../priv/bcrypt] Error 1
make: Leaving directory '/root/elixir-china/deps/bcrypt/c_src'
===> Hook for compile failed!

*\* (Mix) Could not compile dependency :bcrypt, "/root/.mix/rebar3 bare compile --paths "/root/elixir-china/_build/dev/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile bcrypt", update it with "mix deps.update bcrypt" or clean it with "mix deps.clean bcrypt"
root@hb:~/elixir-china#

**Comment by tony612** [comment]
pull 一下 master，更新 deps，再试试？

**Comment by tony612** [comment]
应该是 bcrypt 里 C 拓展编译的问题。可以考虑把 bcrypt 删了重新编译 `rm -rf deps/bcrypt` 。编译后应该会生成一些 `.o` 文件：
```
$ ls -lh deps/bcrypt/c_src/
total 224
-rw-r--r--  1 tony  staff   229B Mar 28 23:14 Makefile
-rw-r--r--  1 tony  staff   3.4K Mar 28 23:14 async_queue.c
-rw-r--r--  1 tony  staff   2.8K Mar 28 23:14 async_queue.h
-rw-r--r--  1 tony  staff   2.7K Mar 28 23:15 async_queue.o
-rw-r--r--  1 tony  staff   7.8K Mar 28 23:14 bcrypt.c
-rw-r--r--  1 tony  staff   4.9K Mar 28 23:15 bcrypt.o
-rw-r--r--  1 tony  staff   6.9K Mar 28 23:14 bcrypt_nif.c
-rw-r--r--  1 tony  staff   765B Mar 28 23:14 bcrypt_nif.h
-rw-r--r--  1 tony  staff   7.4K Mar 28 23:15 bcrypt_nif.o
-rw-r--r--  1 tony  staff   6.2K Mar 28 23:14 bcrypt_port.c
-rw-r--r--  1 tony  staff   5.4K Mar 28 23:15 bcrypt_port.o
-rw-r--r--  1 tony  staff    23K Mar 28 23:14 blowfish.c
-rw-r--r--  1 tony  staff    14K Mar 28 23:15 blowfish.o
-rw-r--r--  1 tony  staff   3.6K Mar 28 23:14 erl_blf.h
```
如果还是不行的话，那估计是你本地 C 环境有问题了。

先关了，还有问题的话，到时再贴错误出来吧
