### ISSUE TITLE
注册时邮箱重复，应该给出正确的错误提示

### ISSUE THREAD

**Issue by tony612** [elixir-cn/elixir-china#88]
现在如果邮箱重复，会报错
![screen shot 2016-12-23 at 11 27 02 am](https://cloud.githubusercontent.com/assets/1253659/21446588/e792dfce-c902-11e6-8cbe-3ba9c3cccbb3.png)
应该给出错误提示
@yfractal

**Comment by h1u2i3** [comment]
https://github.com/elixir-cn/elixir-china/blob/master/web/models/user.ex#L23
```elixir
 |> unique_constraint(:email, name: :users_email_key)
```
